name: Build & Publish admin service Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'services/admin/**'

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./services/admin/
          push: true
          tags: jishnusv23/Ecommerce-admin-service:latest